"""Deterministically bundle the modular Luau source. No network dependency."""
from pathlib import Path
import hashlib

root = Path(__file__).resolve().parent
modules = [
    ('Runtime','core/Runtime.lua'), ('Theme','core/Theme.lua'),
    ('DiscordAsset','core/DiscordAsset.lua'), ('Icons','core/Icons.lua'), ('State','core/State.lua'),
    ('UI','core/UI.lua'), ('Input','core/Input.lua'), ('Assets','core/Assets.lua'),
    ('Popup','core/Popup.lua'), ('Section','components/Section.lua'),
    ('Feedback','components/Feedback.lua'), ('Controls','components/Controls.lua'), ('Choice','components/Choice.lua'),
    ('MobileLayout','layouts/Mobile.lua'), ('Renderer','Renderer.lua'), ('Manifest','Manifest.lua'), ('App','App.lua'),
]
parts = ['-- SERENITY CONCEPT 02 / ISOLATED UI PREVIEW\n-- Generated by prototype/build.py; edit source modules instead.\nlocal M = {}\n']
for name, path in modules:
    parts.append('-- MODULE: '+path+'\nM.'+name+' = (function()\n'+(root/path).read_text().rstrip()+'\nend)()\n')
parts.append('''
local env = (getgenv and getgenv()) or _G
local key = '__SERENITY_CONCEPT_02'
local old = env[key]
if old and type(old.Destroy)=='function' then old:Destroy() end
local app = M.App(M, env.SerenityConceptOptions or {})
env[key] = app
app.Runtime:OnDestroy(function() if env[key]==app then env[key]=nil end end)
return app
''')
output=root/'dist/SerenityConcept.lua'
output.parent.mkdir(exist_ok=True)
output.write_text('\n'.join(parts))
print(output.name, hashlib.sha256(output.read_bytes()).hexdigest())

# Integration library returns Build without mounting the generic demo.
bridge=(root/'PhonkBridge.lua').read_text()
(root/'dist/SerenityPhonkUI.lua').write_text('\n'.join(parts[:-1])+'\n'+bridge)
